### ISSUE TITLE
/adduser not working as expected. (basically not working at all)

### ISSUE THREAD

**Issue by CasparN** [TrinityyTeam/issues#61]
**Describe the bug**
It says the ticket isn't a ticket when trying to add a user.

**To Reproduce**
Steps to reproduce the behaviour:
1. An open ticket
2. Run command ``/adduser``
4. See the error

**Expected behaviour**
The specified user gets added to the ticket.

**Screenshots**
![image](https://user-images.githubusercontent.com/72972596/164705292-124b87e5-aca7-4f7b-b0dc-cabd5d654049.png)

**Additional context**
I cri

**Comment by SliceCraft** [comment]
Searching for a ticket has been changed to first check on the channel you are in and then what ticket a user owns.
Because of this a user which only has one ticket can add and remove users while outside of the ticket channel while mods or support can add and remove users while in a ticket without having to specify the ticket.
